#!/bin/sh

early_exit=0

# Default to using sudo on Linux
sudo=''
if [ "$(uname)" = 'Linux' ]; then
  sudo='sudo'
  echo "Looks like you're on a Linux machine. Running all docker-compose commands with sudo..."
fi

# Only run if there are files staged for commit
changed_files=$(git diff --cached --name-only --diff-filter=ACM | paste -s -d' ' -)
if [ -n "$changed_files" ]; then

  # rubocop
  $sudo docker-compose run web rubocop $changed_files
  if [ $? -ne 0 ]; then
    >&2 echo "Rubocop check failed, try running: bundle exec rubocop --auto-correct $changed_files"
    early_exit=$(($early_exit + 1))
  else
    >&1 echo "Rubocop check complete"
  fi

  # Run `rake notes` job
  $sudo docker-compose run web rake notes > TODO
  if [ $? -ne 0 ]; then
    >&2 echo "rake notes > TODO: failed"
    early_exit=$(($early_exit + 1))
  else
    git add TODO
    >&1 echo "TODO notes added"
  fi

  # Run 'annotate' gem (populates app/models, spec/ with schema changes)
  annotate_results=$($sudo docker-compose run web annotate)
  if [ -n "$annotate_results" ]; then
    annotated_files=$(echo $annotate_results | awk -FAnnotated '{print $2}' | awk -F: '{print $2}' | sed s/,//g)
    if [ -z "$annotated_files" ]; then
      >&1 echo 'No files annotated'
    else
      >&2 echo "Files updated with annotate! please git-add them and commit again"
      >&2 echo "Run:\n  git add -p $annotated_files"
      early_exit=$(($early_exit + 1))
    fi
  else
    >&1 echo 'No files annotated'
  fi

  if [ $early_exit -ne 0 ]; then
    >&2 echo '** git-commit ABORTED - see above **'
    exit 1
  fi
fi
