issuesOpened: >
  <img src="https://i.giphy.com/media/osjgQPWRx3cac/giphy.webp" height=200 />
  <br />
  Thank you for raising an issue! We will get back to you as soon as possible.
  <br />
  Please make sure you provided as much context about the issue as possible.
  <br />
  Best,
  <br />
  @rubyforgood/diaper-team
pullRequestOpened: >
  <img src="https://i.giphy.com/media/osjgQPWRx3cac/giphy.webp" height=200 />
  <br />
  Thank you for your pull request!
  <br />
  Please make sure you have followed our contributing guidelines. We will review it as soon as possible. 
  <br />
  Best,
  <br />
  @rubyforgood/diaper-team
