---
glob: "**/*.{html,text,js}{+*,}.erb"
exclude:
  - "**/vendor/**/*"
  - "**/node_modules/**/*"
EnableDefaultLinters: true
linters:
  AllowedScriptType:
    enabled: true
    allowed_types:
      - "application/json"
      - "text/javascript"
      - "text/html"
      - "module"
      - "esms-options"
    disallow_inline_scripts: false
