version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: '/usr/src/app'
    command: [rails, server, -p, '3000', -b, 0.0.0.0]
    links:
      - postgres
    environment:
      - PG_USERNAME=postgres
      - PG_HOST=postgres
      - DIAPER_PARTNER_URL=http://diaperpartner:3000
      - DIAPER_PARTNER_SECRET_KEY=secretkey123

  test:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    working_dir: '/usr/src/app'
    command: [rake, spec]
    links:
      - postgres
    environment:
      - PG_USERNAME=postgres
      - PG_HOST=postgres
      - RAILS_ENV=test

  postgres:
    image: postgres:9.5
    ports:
      - "5432"
