name: Missing Components for Redesign
description: A page contains components that are not included in Mosaic's admin dashboard template
title: "[FEv2]: <view> Page"
labels:
  - Design
  - Front-end v2
assignees:
  - meg-gutshall
  - justalilhonest
body:
- type: markdown
  attributes:
    value: |
      This issue is a child of Meta issue #2965: Evaluate template for missing components.

      This issue identifies a page in the app which has a component that is **not** included in the [Mosaic](https://cruip.com/mosaic/) admin dashboard template.
- type: dropdown
  attributes:
    label: Which part of the app is this issue for?
    description: Pick one.
    options:
      - Human Essentials
      - Partner Base
  validations:
    required: true
- type: input
  attributes:
    label: Page
    description: The name of the view file or partial that this issue focuses on.
    placeholder: |
      `audits/show.html.erb` - OR - `partners/_table.html.erb`
  validations:
    required: true
- type: input
  attributes:
    label: URL
    description: The link to the page on staging where this component renders.
    placeholder: |
      https://staging.humanessentials.app/admin/account_requests?organization_id=admin
  validations:
    required: true
- type: textarea
  attributes:
    label: Missing Components
    description: A description of which components from the page are missing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: |
      Include screenshots if you think they'll be helpful.

      Tip: You can attach images by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the missing components!
  validations:
    required: false
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/rubyforgood/human-essentials/blob/1f90a512824d8fae1951c7517cdcf491ca3218dc/code-of-conduct.md)
    options:
      - label: I've read the Code of Conduct and understand my responsibilities as a member of the Ruby for Good community
        required: true
