# Puts every state name ever into a single file, so we don't have to do it anywhere else.
module AddressHelper
  def us_states
    [
      %w(AK AK),
      %w(AL AL),
      %w(AR AR),
      %w(AZ AZ),
      %w(CA CA),
      %w(CO CO),
      %w(CT CT),
      %w(DC DC),
      %w(DE DE),
      %w(FL FL),
      %w(GA GA),
      %w(HI HI),
      %w(IA IA),
      %w(ID ID),
      %w(IL IL),
      %w(IN IN),
      %w(KS KS),
      %w(KY KY),
      %w(LA LA),
      %w(MA MA),
      %w(MD MD),
      %w(ME ME),
      %w(MI MI),
      %w(MN MN),
      %w(MO MO),
      %w(MS MS),
      %w(MT MT),
      %w(NC NC),
      %w(ND ND),
      %w(NE NE),
      %w(NH NH),
      %w(NJ NJ),
      %w(NM NM),
      %w(NV NV),
      %w(NY NY),
      %w(OH OH),
      %w(OK OK),
      %w(OR OR),
      %w(PA PA),
      %w(RI RI),
      %w(SC SC),
      %w(SD SD),
      %w(TN TN),
      %w(TX TX),
      %w(UT UT),
      %w(VA VA),
      %w(VT VT),
      %w(WA WA),
      %w(WI WI),
      %w(WV WV),
      %w(WY WY)
    ]
  end
end
