on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'
  workflow_dispatch: # Enable manual runs of the bot

jobs:
  add_help_wanted_labels:
    runs-on: ubuntu-latest
    name: Add help wanted labels
    steps:
      - name: Add help wanted labels
        uses: rubyforgood/add-label-to-cards@v2.1
        id: add-help-wanted-labels
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          column_name: 'To do'
          label_to_add: 'Help Wanted'
          project_name: 'Essentials Project Board'