#name: capistrano deploy
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 2.7.2
#          bundler-cache: true
#      - uses: miloserdow/capistrano-deploy@master
#        env:
#          BRANCH: main
#        with:
#          target: staging
#          deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}